### PR TITLE
Create Installation_BastilleBSD.md

### PR DESCRIPTION
**Pull request by leandroscardua**
HI There,

Thank you for your hard work with Jellyfin and also with the dotnet port to Freebsd.
I really appreciate it.
I'm opening that commit to let people know about the other possibility to install jellyfin using BastilleBSD, a management of jails on FreeBSD.

### CODE REVIEW

**Comment by Thefrank** [comment]
Looks good! Let me know when you are ready to merge this.

Just as a heads up: the current version (10.8.9) and future versions of Jellyfin will be on the pkg mirrors. See here: https://www.freshports.org/multimedia/jellyfin/
The port is currently in `latest` but should also be in the next `quarterly` whenever its next window closes.

**Comment by leandroscardua** [comment]
Thank you for your update on it.

I'll change the PR and also change the template on BastilleBSD to reflect it, and use the port for it.
When I finished it, I'll open this PR or do you prefer to close this one and open a new one?

**Comment by Thefrank** [comment]
It is up to you how you want to handle the PR. 
Github tracks the branch associated with the PR and not individual commits so you can continue to make changes to the branch until the PR is merged or closed.

**Comment by Thefrank** [comment]
@leandroscardua There is now a [quarterly ](https://www.freshports.org/multimedia/jellyfin/)release for jellyfin if you want to use the official pkg mirrors instead of downloading from GH. Also, let me know if you want to make changes with this PR or if you are all set with it

**Comment by leandroscardua** [comment]
Thank you for your update on it.

I just changed the PR to introduce the installation and update using the quarterly repo.
Thank you for the information
Fell free to review it and let me know, if I need to change anhything

**Comment by leandroscardua** [comment]
Hi @rucko24 ,

The bastille template will use quarterly repo, no need additional step, simple pkg install and etc ...
I just tested all good

**Comment by Thefrank** [comment]
LGTM! Thanks!

**Pull request merged**
