### PR TITLE
Updated driver install and new Troubleshooting section.

### PR DESCRIPTION
**Pull request by spz2k9**
Little information update.

### CODE REVIEW

**Comment by Thefrank** [comment]
LGTM!
Let me know when you are ready to merge this

**Comment by spz2k9** [comment]
I think it's all good. I did a last fix for VAAPI to be in capital everywhere except in command line.

**Comment by spz2k9** [comment]
I've re-read the page and everything is good now. You can do a merge.

**Comment by Thefrank** [comment]
Thanks again!

**Pull request merged**
